let books = [
    {id: "1", BookName:"The fault in our stars", Book_Author:"John Green", Date_Published: "2016", Book_Pages: "378", Genres: "Drama, Romance, Teen", Description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quaerat odit libero similique cumque recusandae fugit, quos ducimus perspiciatis aliquid, ratione possimus quae reprehenderit iure quod optio harum porro", img1: "images/book1.jpg", img2: "images/book1back.jpg"},
    {id: "2", BookName:"Divergent", Book_Author:"Veronica Roth", Date_Published: "2014", Book_Pages: "590", Genres: "Fiction, Romance", Description: "Eiojcs ipsum dolor sit amet consectetur adipisicing elit. Voluptatum laborum incidunt voluptate cupiditate quasi temporibus possimus quis, rerum quaerat, natus harum mollitia sit veniam perspiciatis, corporis officia similique quia minus?", img1: "images/book2.jpg", img2: "images/book2back.jpg"},
    {id: "3", BookName:"It ends with us", Book_Author:"Colleen hoover", Date_Published: "2019", Book_Pages: "378", Genres: "Drama, Romance, Teen", Description: "Kohem, ipsum dolor sit amet consectetur adipisicing elit. Facilis repellendus nobis dolores ut eum debitis, repudiandae iure, beatae ipsam, cupiditate commodi aliquam laboriosam? Ipsam libero, enim expedita non suscipit cumque?", img1: "images/book3.jpg", img2: "images/book3back.jpg"},
    {id: "4", BookName:"November 9", Book_Author:"Colleen hoover", Date_Published: "2020", Book_Pages: "478", Genres: "Drama, Romance", Description: "Johsn ipsum dolor sit amet consectetur adipisicing elit. Voluptatem adipisci, vel error quibusdam inventore quaerat minus animi eveniet sed esse voluptatum voluptates autem possimus praesentium ratione reprehenderit eligendi enim nostrum!", img1: "images/book4.jpg", img2: "images/book4back.jpg"},
    {id: "5", BookName:"The Alchemist", Book_Author:"Paulo Coelho", Date_Published: "2012", Book_Pages: "220", Genres: "Drama, Self Discovery", Description: "Yohsc ipsum dolor sit amet consectetur adipisicing elit. In maiores animi possimus, iusto tempora, quisquam nemo laboriosam dolor libero assumenda pariatur tempore autem, fugit quis neque quaerat sit nostrum fugiat.", img1: "images/book5.jpg", img2: "images/book5back.jpg"},
    {id: "3", BookName:"It ends with us", Book_Author:"Colleen hoover", Date_Published: "2019", Book_Pages: "378", Genres: "Drama, Romance, Teen", Description: "Kohem, ipsum dolor sit amet consectetur adipisicing elit. Facilis repellendus nobis dolores ut eum debitis, repudiandae iure, beatae ipsam, cupiditate commodi aliquam laboriosam? Ipsam libero, enim expedita non suscipit cumque?", img1: "images/book3.jpg", img2: "images/book3back.jpg"},
    {id: "5", BookName:"The Alchemist", Book_Author:"Paulo Coelho", Date_Published: "2012", Book_Pages: "220", Genres: "Drama, Self Discovery", Description: "Yohsc ipsum dolor sit amet consectetur adipisicing elit. In maiores animi possimus, iusto tempora, quisquam nemo laboriosam dolor libero assumenda pariatur tempore autem, fugit quis neque quaerat sit nostrum fugiat.", img1: "images/book5.jpg", img2: "images/book5back.jpg"},
    {id: "4", BookName:"November 9", Book_Author:"Colleen hoover", Date_Published: "2020", Book_Pages: "478", Genres: "Drama, Romance", Description: "Johsn ipsum dolor sit amet consectetur adipisicing elit. Voluptatem adipisci, vel error quibusdam inventore quaerat minus animi eveniet sed esse voluptatum voluptates autem possimus praesentium ratione reprehenderit eligendi enim nostrum!", img1: "images/book4.jpg", img2: "images/book4back.jpg"},
    {id: "2", BookName:"Divergent", Book_Author:"Veronica Roth", Date_Published: "2014", Book_Pages: "590", Genres: "Fiction, Romance", Description: "Eiojcs ipsum dolor sit amet consectetur adipisicing elit. Voluptatum laborum incidunt voluptate cupiditate quasi temporibus possimus quis, rerum quaerat, natus harum mollitia sit veniam perspiciatis, corporis officia similique quia minus?", img1: "images/book2.jpg", img2: "images/book2back.jpg"},
    {id: "3", BookName:"It ends with us", Book_Author:"Colleen hoover", Date_Published: "2019", Book_Pages: "378", Genres: "Drama, Romance, Teen", Description: "Kohem, ipsum dolor sit amet consectetur adipisicing elit. Facilis repellendus nobis dolores ut eum debitis, repudiandae iure, beatae ipsam, cupiditate commodi aliquam laboriosam? Ipsam libero, enim expedita non suscipit cumque?", img1: "images/book3.jpg", img2: "images/book3back.jpg"},
    {id: "4", BookName:"November 9", Book_Author:"Colleen hoover", Date_Published: "2020", Book_Pages: "478", Genres: "Drama, Romance", Description: "Johsn ipsum dolor sit amet consectetur adipisicing elit. Voluptatem adipisci, vel error quibusdam inventore quaerat minus animi eveniet sed esse voluptatum voluptates autem possimus praesentium ratione reprehenderit eligendi enim nostrum!", img1: "images/book4.jpg", img2: "images/book4back.jpg"},
    {id: "5", BookName:"The Alchemist", Book_Author:"Paulo Coelho", Date_Published: "2012", Book_Pages: "220", Genres: "Drama, Self Discovery", Description: "Yohsc ipsum dolor sit amet consectetur adipisicing elit. In maiores animi possimus, iusto tempora, quisquam nemo laboriosam dolor libero assumenda pariatur tempore autem, fugit quis neque quaerat sit nostrum fugiat.", img1: "images/book5.jpg", img2: "images/book5back.jpg"},
    {id: "3", BookName:"It ends with us", Book_Author:"Colleen hoover", Date_Published: "2019", Book_Pages: "378", Genres: "Drama, Romance, Teen", Description: "Kohem, ipsum dolor sit amet consectetur adipisicing elit. Facilis repellendus nobis dolores ut eum debitis, repudiandae iure, beatae ipsam, cupiditate commodi aliquam laboriosam? Ipsam libero, enim expedita non suscipit cumque?", img1: "images/book3.jpg", img2: "images/book3back.jpg"},
    {id: "5", BookName:"The Alchemist", Book_Author:"Paulo Coelho", Date_Published: "2012", Book_Pages: "220", Genres: "Drama, Self Discovery", Description: "Yohsc ipsum dolor sit amet consectetur adipisicing elit. In maiores animi possimus, iusto tempora, quisquam nemo laboriosam dolor libero assumenda pariatur tempore autem, fugit quis neque quaerat sit nostrum fugiat.", img1: "images/book5.jpg", img2: "images/book5back.jpg"},
    {id: "4", BookName:"November 9", Book_Author:"Colleen hoover", Date_Published: "2020", Book_Pages: "478", Genres: "Drama, Romance", Description: "Johsn ipsum dolor sit amet consectetur adipisicing elit. Voluptatem adipisci, vel error quibusdam inventore quaerat minus animi eveniet sed esse voluptatum voluptates autem possimus praesentium ratione reprehenderit eligendi enim nostrum!", img1: "images/book4.jpg", img2: "images/book4back.jpg"},
    {id: "2", BookName:"Divergent", Book_Author:"Veronica Roth", Date_Published: "2014", Book_Pages: "590", Genres: "Fiction, Romance", Description: "Eiojcs ipsum dolor sit amet consectetur adipisicing elit. Voluptatum laborum incidunt voluptate cupiditate quasi temporibus possimus quis, rerum quaerat, natus harum mollitia sit veniam perspiciatis, corporis officia similique quia minus?", img1: "images/book2.jpg", img2: "images/book2back.jpg"},
    {id: "3", BookName:"It ends with us", Book_Author:"Colleen hoover", Date_Published: "2019", Book_Pages: "378", Genres: "Drama, Romance, Teen", Description: "Kohem, ipsum dolor sit amet consectetur adipisicing elit. Facilis repellendus nobis dolores ut eum debitis, repudiandae iure, beatae ipsam, cupiditate commodi aliquam laboriosam? Ipsam libero, enim expedita non suscipit cumque?", img1: "images/book3.jpg", img2: "images/book3back.jpg"},
    {id: "4", BookName:"November 9", Book_Author:"Colleen hoover", Date_Published: "2020", Book_Pages: "478", Genres: "Drama, Romance", Description: "Johsn ipsum dolor sit amet consectetur adipisicing elit. Voluptatem adipisci, vel error quibusdam inventore quaerat minus animi eveniet sed esse voluptatum voluptates autem possimus praesentium ratione reprehenderit eligendi enim nostrum!", img1: "images/book4.jpg", img2: "images/book4back.jpg"},
    {id: "5", BookName:"The Alchemist", Book_Author:"Paulo Coelho", Date_Published: "2012", Book_Pages: "220", Genres: "Drama, Self Discovery", Description: "Yohsc ipsum dolor sit amet consectetur adipisicing elit. In maiores animi possimus, iusto tempora, quisquam nemo laboriosam dolor libero assumenda pariatur tempore autem, fugit quis neque quaerat sit nostrum fugiat.", img1: "images/book5.jpg", img2: "images/book5back.jpg"},
    {id: "3", BookName:"It ends with us", Book_Author:"Colleen hoover", Date_Published: "2019", Book_Pages: "378", Genres: "Drama, Romance, Teen", Description: "Kohem, ipsum dolor sit amet consectetur adipisicing elit. Facilis repellendus nobis dolores ut eum debitis, repudiandae iure, beatae ipsam, cupiditate commodi aliquam laboriosam? Ipsam libero, enim expedita non suscipit cumque?", img1: "images/book3.jpg", img2: "images/book3back.jpg"}
];
function loadBooks(){
    for(let i = 0; i < books.length/5; i++){
        document.getElementById("main-block").innerHTML += "<div style='width:100%; height: 370px; margin-top:40px; margin-bottom:60px; background-color: rgb(240, 240, 240);'>";
        let k = 0;
        for(let j = i * 5; j < ((i + 1) * 5); j++){
            document.getElementById("main-block").getElementsByTagName("div")[i*6].innerHTML += "\n\t<div class='article2-block-parts'>";
            document.getElementById("main-block").getElementsByTagName("div")[i*6].getElementsByTagName("div")[k].innerHTML += "\n\t\t<img style='height:280px;' class='article-img' src='" + books[j].img1 + "' alt='book'>";
            document.getElementById("main-block").getElementsByTagName("div")[i*6].getElementsByTagName("div")[k].innerHTML += "\n\t\t<p class='article-img-title'>" + books[j].BookName + "</p>";
            document.getElementById("main-block").getElementsByTagName("div")[i*6].getElementsByTagName("div")[k].innerHTML += "\n\t\t<button onclick= 'openBookDetails(" + books[j].id + ")' type='button' class='btn btn-dark article-btn'>View</button>\n";
            k++;
        }
        console.log(document.getElementById("main-block").innerHTML + '\n\n\n');
    }
}

function openBookDetails(bookNum){
    const page = window.open('showBookDetails.html');
    page.addEventListener('DOMContentLoaded', () => {
        bookNum--;
        page.document.getElementById("i_img1").src = books[bookNum].img1;
        page.document.getElementById("i_img2").src = books[bookNum].img2;
        page.document.getElementById("expandedImg").src = books[bookNum].img1;
        page.document.getElementById("i_book-title").innerHTML += books[bookNum].BookName;
        page.document.getElementById("i_book_author").innerHTML += books[bookNum].Book_Author;
        page.document.getElementById("i_date_published").innerHTML += books[bookNum].Date_Published;
        page.document.getElementById("i_book_pages").innerHTML += books[bookNum].Book_Pages;
        page.document.getElementById("i_genres").innerHTML += books[bookNum].Genres;
        page.document.getElementById("i_book-description").innerHTML += books[bookNum].Description;
    })
}
